# Spring properties
spring:
  application:
    name: cmplWeb
  logging:
    level:
      root: INFO
      org.springframework.web: ERROR
      org.hibernate: ERROR
    pattern:
      console: "%d{ISO8601} %5p [%25c{1}] - %m | [%thread]%n"
      file: "%d{ISO8601} %5p [%25c{1}] - %m | [%thread]%n"
    path: ${basePath}/logs
    file: ${logging.path}/web.log
  boot:
    admin:
      client:
        url: http://localhost:8702
        username: user
        password: password
  resources:
    cache:
      cachecontrol:
        max-age: 30D


# HTTP Server
server:
  port: 3233  # HTTP (Tomcat) port



basePath: C:/volume1/cmpl/web
baseUrl: http://localhost:3232
mailFrom: contact@somewebsite.com

reset:
  token:
    secret:
      string: fa19zb7e-0371-4cfc-b8fa-6f96ba3b6b51
      integer: 3474194


management:
  endpoints:
    web:
      exposure:
        include: '*'
