language: java
jdk: oraclejdk8
sudo: true
addons:
  sonarcloud:
    organization: "tacs-utn"
    token: $SONAR_TOKEN
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar org.jacoco:jacoco-maven-plugin:report coveralls:report

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: tacs-event-manager