language: java

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_OPTS=-Xmx512m

sudo: false

before_script:
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true

after_success:
  - mvn clean test jacoco:report coveralls:report