language: java
script: mvn clean package
jdk:
  - oraclejdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${sonar.login}