language: java
addons:
    sonarcloud:
        organization: volkoedov-github
        token:
            secure: $SONAR_TOKEN
script:
- mvn -f ./tutorial/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
