sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a434c0997c2c1629fef2
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: dU7Bqd1NMbPGNdG1iyxXm+TQT+OnZzSWXnQVD2wDyMOr3LY9/3yvG3acW329UtFmPi8WzgGeJsdTCm0C9TJ5bz636VjpaTyDw/8QqXyD8b3fCrUWJjnQ1Nyc3100XxOTxChTuQxPBJrqSvZoriaFuYCuKtFKStELrz0XZ1YeHXWOL/7RTTKnQkCwj0OfGCqlpIiycv1dtSYqQ/CkXGx9Fo8OFfis/AeaqYW2VXMwLqMqopHFxTGmQ223pEi4Z9n968IrrGN0c5/kHFpT7IoO1JWwW92mhhfi1fvbQ4hXUT2ji+kKGc300zE+jxrd/e2n+9fxWZlceNf4zQHMcafXe+iw3h/b6EUJu1q+RGjmf72P8VVlccXJLw6OUC2Zy8rYQ/YuFSJGOdYlippSBYilvm/6ZETDiddTDGz/EdRALgjkLqtyO9dhsaMUAesbODYkRi8FEVnKUGceYn4BqVrrcC4huBpaDZzOg0JgpuRMJVgf2JlVmEuYEO55f3detso/3hO4ls4iBuhCHiQvlqsd/lNpY3x9k+/68QZ8Rz8UT2kdG7dctyUgP0tHJXM58SpxXas4S+bMrO3McYdRacqenyI/rnaySbiN+QcxQdiDGp+IRbEk63jK4/2qzvQWvBTBUwm2kmjTmVdi2TM0uFkX3bQ1kj2D/4+jrghpZVzyuWs=
  - secure: wmkRfFsgDf00lrpwn3oKJvL3P2KmjpY+LWumsVPXf6qUu9inxY0vZI2Txp86IbQEFPMj5a3Cx8hmx1CBnbyXLuv0H1kZRKRmbFr/WSwrKZc25U/VJU0/qKxHjeQy3XNbpy7ZcA4yCFn3WjGIPzQihnUhSiqnMDiUT+91ZoJ7ASyOzjO7/KKmjfEA4+xQjgcsKRs+h7skmW4xK0fXpVU+zCJKA/1+yD+G4njM5fD5mEYE820rLpTFISFSEteQa799jR+MP/Xpy6AxK/WVUVfERxcr0rjBvQ183YccIefzkIBceEq2kGycNV8BP6c3hhAMRtvD09vIRcxQXrCuTpdwOihtaRZyTKtbblRq7QbbkZ6cO2KVCt5ce9Z7xClkGAFKiso/rnwEflYvGHipP2L/FG0BVfvkm1x0YhmlO2XHI4xJkgakDl3Km8a6C4N4UqDYPkwaGmTawenR8K99px83xJhvYKZtQiB77CPKizCMFhHYzWR8ozal99AeAMzoYIpF791kV4fMLj2puGLjfOKyFwImnmd7syhqK/SzmtPTPAJnOTY6iu8yzucshXyuA5j96dmTHqcLB32wNADETf+38Cm1lNCGq8/g/lwKaZ3cxvyU3BDPwiRDfaDBiRM0KAij8rxM3sNoaXB5rKgJvgD7T+7sGfOxqgnBrLOPcz4WosY=
  - secure: wNH2iIJxKR+ns638P+wZFAF8Xxa8B+my1FJ0Njqg8xnOdD5/1qyp2j/m/nnVBIbZ9tHNJY2AmrOWdWiSikcoHG7OCSybCf4RYL1qZnlsOKceqpZcNHX7N8VwVyHqp58aZS8H242EZGi0ScelL0AEFosc4JorWd1JL+yQek9vfWHoKCl+8bgSLlwZ/03jE6XMCbjc0bcJIhMzEnqDwxNQS67v18h35qMEuG8dSegQCZfhZwUAPLQjP1fbzzwMYdy6p9UdT47jpVTtyT1YnS4II6rfKIQEAl9yukNR6tKChAusY83pIAUREqFlkP/CnX+kbnUifKBJyUW4KO3+51Umh/siIMDMO+NmzsQxY2k79Bn24om7xLmEsYPPPO9wmbMmYKe/S4GWy96TnzcIoU3VvLUfvMgfZiCKsBFKnNCPXChVP4QJRLdwKQp9c7+XokNddBVdMzDt++r3/BAtf02w5xn0Ue3XLJlQ/JxxEXh9WUCe9+R3u0eE4mHtlNbAlieP2QRzCg0KW3Pl7QYxZf4hEhXESnPUyfe2+7ugZM9UceAvZq7N37tggzBvIZI1TBYAoKpkjYZUDBKKFZEVD9WHVQgYtgw0HR2TrsAw9O0xscOzjB/Tqgy0T+6MaCrOzotfaeoEUxCiqHCrv0KG1PLopX41gu9IhdSuTocnujAQ9TE=
  - secure: jIxsaoyy+7+rzVKiHzGhSqWZIXwWAyYNltVNQWMFwbJM8NlDZ5Pn5Ya0o8YRd6OLkcVJj+o7lvHIz7cyCshST+IiFQc1UnQonr1HIEYwTH0nXjz82RIjGMMPuYlj+9RYptJPVD+KdzUKgwhITH+blUgH1ygs8uvta1dw5MhfVmTPb4lnLV26Xt0zv+EfUfpBP0LX9uVN5p53MhufN6z46QuNxTpoBT53E5PjpujB4djCO9Z5AvqfKMeA0qUwCvJ9PXbM9NQxOA3a9eSd6/hhuRb2rEOk6qF8QvG4DAtwYfuR6K7eHeKsg4usUgo03l/yMqervdc5+0NVQkllD/V46vWoVL/UtrwBg1o+gglZg5TW02cmUpbrQ2UZWHeTXPupeqJXWV78TzL6Nwz4VDkPmIHmxVrBkaiX8ePpQonOcH4D9LfVg6XjCOWXYm8orSE+f23COgt2m39itKEk4ikM/HkOTFjuz6H/AYYNbcli+dcpA41O+5+DadZFftRcsYizsiSq+gkdHbwJD4gnwcQfEesKA2TIGWAMWrrJ/zFpw/+7m6sTIldm0FvtV6ZFFTcWyf7lYYtTK950xNqdQlKEo7/VZ76yyEnoyJwgYdOCVyZ9Dc90wgcCQx2mxpnRCP+8I3HN7efh786294ioSeJ5DO/H//RsLQ16w36uv2n9/Mw=
  - secure: HL/LyFmT8nb4zVqF7t1hWidwqZd2mYAGJHI/PldDtO914zBMvBtsSWPENg63KGbAJIC9FdcRVRXLOi7+YurkjJ28nKraxvPCS7xX/t8dBDyq5gzgbS54io5JVyZQpbJbgs7WklCKIDpxc9j6Puop1nOaKhhW3RkAnqASRYAeWSD0zju2xanozBkzMKim8GUSFExjBpq0NbUGf3JsuiD6X7H/uOom+iEIoMGFj+nN/o4fGYVGcnOxeaIrpHcIWVXaXLvyq1TYa+Eczgini/9utIponqpE3Ub4NBRnj/OZcg5ynthLh+S9egSQnd5pxtWp5tYDRITABD1zIic0O9Vvi6KqLN2zyFhpjSOh3OWIm+lmaU+kYCHlvYrhXNgefkA9CMOHBF3NsKqJ0FxR9jI7wlcR5aFIlzJ8FGrke68SeBdUKo8OoPeDKJY31uPzxNjWsn1vu+9Cry7DXZmib5+W9rthpW4u6KMUhx93mAQdhofT4+IhtBPmcSYPDvwz9DbcNtH7Xn0oFw5T5BnN3ZrRxVUDaCJRYcj3/6UJ++MiIj/3sRghAVwk2VsHRxxqRg21jlwd052g1Ctp6r6hIBU/TV2hXw+fkEYoz90CCsT1w5YUNYDbFSM42Q55vw+gSXFH4R9bq+RE7Zo5XpEWbyPpCf9t1HcKvkbL+VxECCiXaOE=
