id: alien4cloud-yorc-plugin
name: Yorc Orchestrator Provider
version: ${project.version}
description: >
  Plugin that contains a single paas provider for deployments on Hpc env.
configuration_class: org.ystia.yorc.alien4cloud.plugin.YorcPluginConfiguration
component_descriptors:
  - bean_name: yorc-orchestrator-factory
    name: Yorc Orchestrator Factory
    description: >
      Alien Plugin for Yorc
  - bean_name: yorc-kubernetes-modifier
    name: Yorc Modifier for Kubernetes
    description: >
      Yorc Modifier for Kubernetes
dependencies:
  - alien4cloud-kubernetes-plugin
